import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import NavigationBar from './components/navigationBar/navigationBar';
import {AuthProvider} from './context/authContext';
import { PokemonContextProvider } from "./context/pokemonContext";
import { Filter } from "./context/filter/filter";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
            <body className={inter.className}>
              <AuthProvider>
                <PokemonContextProvider>
                  <NavigationBar />
                  {children}
                </PokemonContextProvider>
              </AuthProvider>  
            </body>
    </html>
  );
}
